#pragma once
#include "CoreMinimal.h"
#include "EGothicLogCategory.generated.h"

UENUM(BlueprintType)
enum class EGothicLogCategory : uint8 {
    Core,
    AI,
    Combat,
    Locomotion,
    AngelscriptGAS,
    Player,
    Input,
    GameplayPointSystem,
    NavigationData,
    NavigationDataCreation,
    AINavigation,
    GAS,
    Items,
    Network,
    Magic,
    Camera,
    Sound,
    FX,
    Fishing,
    Animation,
    DataValidation,
    AutomatedTest,
    Spawning,
    ScriptBindings,
    Journal,
    StoryEvents,
    UI,
    Localization,
    Conversation,
    Cinematics,
    Target,
    GameplayCue,
    Environment,
    Quest,
    Resource,
    ProcessingRange,
    Interaction,
    Mod,
    PersistentData,
    LockPick,
    WorldPoint,
    Count,
};

